#? flutter --version                                                                                                       ─╯
# Flutter 3.19.0 • channel stable • https://github.com/flutter/flutter.git
# Framework • revision bae5e49bc2 (3 days ago) • 2024-02-13 17:46:18 -0800
# Engine • revision 04817c99c9
# Tools • Dart 3.3.0 • DevTools 2.31.1

name: example
description: "A new Flutter project that uses heyhub_emoji package."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  heyhub_emoji:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
